version: '3'
services:
  net1:
    image: python:3.6.5
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

    command: bash -c "pip install -r requirements.txt && python plutus.py -m`"